version: '3'

services:
  app:
    image: scnerd/devoted_daily_app
    build: .
    environment:
      DEFAULT_PWD: password
      DB_PASSWORD_FILE: /secrets/db_password
      DIGITAL_BIBLE_KEY_FILE: /secrets/dbk
      DEBUG_MODE: 1
    volumes:
      - './secrets/db_password:/secrets/db_password'
      - './secrets/digital_bible_key:/secrets/dbk'
      - 'static:/static'
      - './media:/media'
    depends_on:
      - postgres
    ports:
      - '127.0.0.1:8000:8000'
    restart: always

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - './proxy.conf:/etc/nginx/conf.d/default.conf'
      - 'static:/static'
      - './media:/media'
    ports:
      - 80:80
    restart: always

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: devotion
      POSTGRES_PASSWORD_FILE: /secrets/db_password
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './secrets/db_password:/secrets/db_password'
    restart: always

volumes:
  pgdata:
  static: