# Generated by Django 2.1 on 2018-08-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotion_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybibleplan',
            name='version',
            field=models.CharField(choices=[('ESV', 'ESV'), ('KJV', 'KJV')], default='ESV', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailybibleplan',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
